# Atividade 1 - Etapa 1

Controle de Poluição Atmosférica\
Professor: Leonardo Hoinaski\
Aluna: Bianca Bonetti Nunes


# Dados Numéricos

In [2]:
# Variável inteira
a = 1 #aqui estamos declarando que a variável "a" recebe o valor 1
print('Valor de a = '+str(a)) # esse código vai escrever o que está em parênteses e ao somar a variavel a é preciso fazer
# a conversão de int(número inteiro) para str (texto)
type(a) #aqui pedimos para o computador informar o tipo de variavel, nesse caso será int (número inteiro)

Valor de a = 1


int

In [3]:
# Variável dupla precisão
b = 1.0 # declarando a variável b como 1.0 
print(b) # pedimos para que o seja escrito o valor de b
type(b) # informa o tipo da variável, nesse caso é float (número decimal)

1.0


float

In [4]:
# Converter float para int
c = int(b) # aqui estamos declarando que a variável c será igual a variável b convertida para int
print(c) # pedimos para que o seja escrito o valor de c
type(c) # informa o tipo da variável, como c é a converção de b para int c é uma variável tipo int

1


int

In [5]:
# Delacrando nan
import numpy as np # estamos importando o pacote numpy (que vai possibilitar utilizar outros tipos de códigos) 
# e informamos que o "apelido" de numpy será "np" para facilitar a escrita do código
d = np.nan #declaramos que a variável d é um "nan" (Not a Number - seria um valor indefinido ou resultados inválidos para operações matemáticas)
print(d) # pedimos para que o seja escrito o valor de d
type(d) # informa o tipo da variável d (float)

nan


float

In [6]:
# Operação com NaN
e = d*1 # declaramos que a variável e é igual a variável d multiplicado com 1
print(e) 
e = d+1 # aqui declaramos que a partir desta linha do código "e" passa a ser igual a "d" somado a 1
print(e)
e = np.nansum([d,1]) # utilizamos o código "nansum", do pacote numpy (apelidado de np), que permite a soma de valores a variáveis NaN
print(e)

nan
nan
1.0


# Dados de Texto

In [7]:
# Declaração de variável texto
f = 'Fábio' # declaramos que "f" é igual ao texto "Fábio" (texto precisa sempre ser colocado entre aspas)
g = "Gabriel" # declaramos que "g" é igual ao texto "Gabriel" ( observe que podemos declarar textos tanto usando aspas simples '' ou duplas "" )
print(f)
print(g)
print(f+g) # aqui somamos os dois textos ( observa-se que não há espaço entre os nomes )
print(f+' '+g) # aqui somamos entre as variaveis o texto ' ' que é o espaço entre os nomes

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


# Dados tipo bool - Lógica

In [8]:
a == 1 
# importante perceber que o sinal = significa no python: 'variável x RECEBE O VALOR y' , 
# já ao utilizar == estamos dizendo: ' x É IGUAL A y ', logo o valor de saída desse comando será TRUE (verdadeiro),
# isso porque anteriormente [2] declaramos que a RECEBE O VALOR 1 (a = 1) 

True

In [9]:
h = (a==1) # declaramos que a varável h recebe o valor de (a==1) que é uma igualdade verdadeira (TRUE)
print(h) 
type(h) # ao declarar que h é a == 1 estamos na verdade fazendo uma "pergunta" ( a variavel "a" é igual a 1?) 
#e o dado de saída será do tipo bool (TRUE ou FALSE)

True


bool

In [10]:
h = (a==2) # aqui estamos perguntando se a variável a é igual a 2, logo h recebe o valor FALSE, pois já é sabido que a é 1
print(h) 
type(h)

False


bool

In [11]:
i = True # declaramos que a variável i recebe o valor TRUE
type(i) # como visto antes os valores TRUE ou FALSE são do tipo bool

bool

In [12]:
ii = 'True' # perceba que ao colocar aspas indicamos um texto e não um valor verdadeiro ou falso
type(ii) # como declaramos um texto o tipo de variável será string (str)

str

# Operação de comparação

In [13]:
# Operação ==
a==b # perguntamos se o valor de a é igual ao de b e o python nos dá a resposta
# (Verdadeiro, pois anteriormente foi declarado que a = 1 e b = 1.0)

True

In [14]:
# Operação ><
a>b # pergunta: a é maior que b? - FALSO

False

In [15]:
# Operação !=
a!=b # Pergunta: a é diferente de b? - FALSO, são iguais (1 = 1.0)

False

In [16]:
# Operação >= ou <=
a>=b # pergunta: a é maior ou igual a b? - VERDADEIRO

True

# Operações matemáticas

In [17]:
# Soma 
a+b # 1 + 1.0

2.0

In [18]:
# Soma e atribui valor
ab = a+b # a variável 'ab' recebe o valor de a+b, logo ab == 2.0
print(ab)

2.0


In [20]:
# Multiplicação
l = a*b 
print("Não use l como nome de variável") # porque não? não entendi.
print(l) # não dá erro, porque não usar? (PERGUNTA PARA O PROFESSOR)
j = a*b
print(j) 

Não use l como nome de variável
1.0
1.0


In [21]:
# Divisão
a/b # a divido por b (1/1.0)

1.0

In [22]:
# Potencia
5**2 # o sinal "**" indica potência

25

In [26]:
# Operações matemáticas com a biblioteca math
import math

math.exp(10) #procura o exponencial de um valor expecífico (e**x) - nesse caso o valor é 10

22026.465794806718

In [27]:
math.exp(0) # nesse caso o valor é 0

1.0

In [28]:
math.exp(a) # nesse caso o valor é 1, pois a == 1

2.718281828459045

In [30]:
math.exp(-10) # ao final da resposta observa-se e-05, significa 10 elevado na -05

4.5399929762484854e-05

In [41]:
import math as mt # aqui apelidamos a biblioteca math de mt
mt.log(c) #logaritimo de c - c == int(b) == 1 (math.log(x[número, base]), não foi add base então a base é e.

0.0

In [42]:
mt.log10(100) #logarítimo na base 10

2.0

# Listas

In [43]:
myFirstList = [1,2,3] # a variável recebe uma lista com os números 1,2,3
print(myFirstList)

[1, 2, 3]


In [44]:
# Acessando valores da lista pelo index
print(myFirstList[0]) # informa o valor que está na posição 0 da lista, nesse caso 1
print(myFirstList[2]) # informa o valor que está na posição 2 da lista, nesse caso 3

1
3


In [46]:
myFirstList==a # pergunta: a variável myFirstList é igual a variavel a? FALSE

False

In [47]:
myFirstList[0]==a # pergunta: o valor da posição 0 da lista (1) é igual ao valor de a (1)? TRUE

True

In [48]:
mySecList = [1,a,'c'] # nessa lista na posição 0 temos o valor 1, na posição 1 o valor da variável a e na posição 2 o texto 'c'.
print(mySecList)

[1, 1, 'c']


In [49]:
type(mySecList) # tipo da variável - list

list

In [50]:
type(mySecList[2]) # tipo do valor declarado na posição 2 da lista - string (texto)

str

In [51]:
type(mySecList[1]) # tipo do valor declarado na posição 1 da lista - int

int

# Caminhos = path

In [52]:
path = r"C:\Users\BiaBN\OneDrive\Documentos\controledepoluicaoatm" # declarando como texto
print(path)
type(path)

C:\Users\BiaBN\OneDrive\Documentos\controledepoluicaoatm


str

In [54]:
path = "C:/Users/BiaBN/OneDrive/Documentos/controledepoluicaoatm" #declarando path como o texto do diretório que estou com as barras ao contrário.
print(path)

C:/Users/BiaBN/OneDrive/Documentos/controledepoluicaoatm


In [55]:
import os #importar biblioteca os
# Listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Atividade1_Etapa1.ipynb',
 'Aula01.ipynb',
 'inputs',
 'README.md',
 'Scripts',
 'venv']

In [57]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0] # arquivo da posição 0

'.git'

In [58]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0] # adiciona ao caminho o primeiro arquivo da pasta

'C:/Users/BiaBN/OneDrive/Documentos/controledepoluicaoatm/.git'

In [59]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0]) #listando os arquivos que estão dentro do primeiro arquivo da pasta declarada no path

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [60]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\BiaBN\\OneDrive\\Documentos\\controledepoluicaoatm'

In [64]:
# Muda de diretório para o caminho 
os.chdir('C:/Users/BiaBN/OneDrive/Documentos/controledepoluicaoatm')

In [65]:
os.getcwd() #Retorna uma string representando o diretório de trabalho atual.

'C:\\Users\\BiaBN\\OneDrive\\Documentos\\controledepoluicaoatm'

In [66]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path): #procura se o new_path já existe, se sim segue para o comando da linha de baixo
    print('diretório já existe')
else: #caso a condição do if seja falsa segue para o comando abaixo, que vai criar o diretório novo
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\BiaBN\OneDrive\Documentos\controledepoluicaoatm/test


In [67]:
# Criando diretório - caso em que o diretório já existe
new_path = os.getcwd()+'/.git'

if os.path.isdir(new_path): #procura se o new_path já existe, se sim segue para o comando da linha de baixo
    print('diretório já existe')
else: #caso a condição do if seja falsa segue para o comando abaixo, que vai criar o diretório novo
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

diretório já existe


In [68]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:#cria arquivo de texto com nome copy
        file.write("Your text goes here")#escreve no arquivo

Criando diretório C:\Users\BiaBN\OneDrive\Documentos\controledepoluicaoatm/test2


# Numpy arrays e Pandas DataFrames

In [70]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n) # a estrutura ndarray armazena os elementos sempre com o mesmo formato

numpy.ndarray

In [71]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [72]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[8.14296811e-01 5.64447231e-01 7.33225293e-01 1.19416109e-01
  7.93412335e-01 9.10781071e-01 8.24693436e-01 4.91307596e-02
  1.07230769e-01 5.29353857e-01]
 [8.48818627e-01 8.37026000e-01 9.37744685e-01 6.05763573e-01
  8.75955122e-01 9.05537973e-01 2.71938678e-01 5.31712556e-01
  5.23347172e-01 4.58864164e-01]
 [7.94224750e-01 2.38018313e-01 3.62301651e-01 2.10969641e-01
  9.11522612e-01 3.85337762e-02 8.80042323e-01 6.55803774e-01
  9.41191224e-02 2.10247020e-01]
 [8.74763687e-01 4.37034061e-01 3.82765866e-01 9.36448130e-01
  4.11340625e-01 9.10317751e-01 7.96088413e-01 6.32207854e-01
  1.72507062e-01 6.24410047e-02]
 [9.42495656e-01 2.51032022e-01 3.69481172e-01 2.02581324e-01
  2.61220580e-01 7.61171172e-01 5.55061780e-01 3.74238052e-01
  7.68258327e-01 5.27000796e-01]
 [4.70991770e-01 8.38652594e-01 6.24714489e-01 2.57016402e-01
  2.15458092e-02 2.56594621e-01 4.66601423e-01 1.55511798e-01
  7.59528253e-01 3.33585016e-01]
 [3.98981020e-01 8.91526002e-01 7.38119554e-01 2.73510616e

In [73]:
# Acessando valores da matriz
n[0,:] #todos os valores da linha 0 da matrix

array([0.81429681, 0.56444723, 0.73322529, 0.11941611, 0.79341234,
       0.91078107, 0.82469344, 0.04913076, 0.10723077, 0.52935386])

In [74]:
n[:,0]#todos os valores da coluna 0 da matrix

array([0.81429681, 0.84881863, 0.79422475, 0.87476369, 0.94249566,
       0.47099177, 0.39898102, 0.72183653, 0.99565903, 0.36127934])

In [76]:
n[:,1:5] #valor de todas as linhas mas somente das colunas 1 até 5

array([[5.64447231e-01, 7.33225293e-01, 1.19416109e-01, 7.93412335e-01],
       [8.37026000e-01, 9.37744685e-01, 6.05763573e-01, 8.75955122e-01],
       [2.38018313e-01, 3.62301651e-01, 2.10969641e-01, 9.11522612e-01],
       [4.37034061e-01, 3.82765866e-01, 9.36448130e-01, 4.11340625e-01],
       [2.51032022e-01, 3.69481172e-01, 2.02581324e-01, 2.61220580e-01],
       [8.38652594e-01, 6.24714489e-01, 2.57016402e-01, 2.15458092e-02],
       [8.91526002e-01, 7.38119554e-01, 2.73510616e-01, 4.50145582e-01],
       [4.43068743e-02, 8.30453497e-01, 7.86706846e-01, 2.53784794e-01],
       [4.28395685e-01, 6.54187222e-01, 9.24696882e-01, 7.60805824e-02],
       [7.83840522e-01, 3.73994216e-05, 3.05634857e-01, 6.45425469e-01]])

In [77]:
n[0,1:5] #valor da linha 0 mas somente das colunas 1 até 5

array([0.56444723, 0.73322529, 0.11941611, 0.79341234])

In [78]:
n[0,-1] #valor da linha 0 coluna -1 (ultima coluna)

0.5293538565038638

In [81]:
n[0,4:-1] #valor da primeira linha começando da coluna 4 e indo até a penultima (final -1)

array([0.79341234, 0.91078107, 0.82469344, 0.04913076, 0.10723077])

In [80]:
n[0,4:] #primeira linha e valores da coluna 4 até a ultima

array([0.79341234, 0.91078107, 0.82469344, 0.04913076, 0.10723077,
       0.52935386])

In [83]:
an = np.log(n*5) #todos os valores da matriz multiplicado por 5
print(an)

[[ 1.40400757  1.03752953  1.29913565 -0.51570326  1.37802569  1.51598518
   1.41669436 -1.40383206 -0.62333414  0.97333976]
 [ 1.44552817  1.43153777  1.54516035  1.1081724   1.47699749  1.51021185
   0.30725923  0.97778567  0.96192769  0.83043686]
 [ 1.37904911  0.17403025  0.59415979  0.05339687  1.51679904 -1.64678221
   1.48165263  1.18754425 -0.75375613  0.04996576]
 [ 1.47563641  0.78169377  0.64910612  1.54377677  0.72110427  1.51547635
   1.38139288  1.15090086 -0.14787919 -1.16409518]
 [ 1.55021394  0.22726314  0.61378242  0.01282404  0.26704782  1.3365409
   1.02076206  0.62657473  1.34580867  0.96888469]
 [ 0.85652325  1.43347918  1.13897736  0.25082254 -2.22813604  0.24918012
   0.84715804 -0.25159576  1.33438015  0.51158039]
 [ 0.69059648  1.49461724  1.30578844  0.31302307  0.81125368  1.47759754
   1.22677865  1.16492611  1.55957865  0.81728561]
 [ 1.28348134 -1.50717752  1.42365457  1.36953832  0.23816928  0.04047504
   1.33227541 -0.57213525  0.77401127  0.88812618]
 